apiVersion: v1
kind: Pod
metadata:
  name: spark-drv-local-env-var
spec:
  containers:
    - name: spark-drv-env-var-configmap
      image: docker.io/jpacerqueira83/spark-k8s:2.4.5
      envFrom:
        - configMapRef:
            name: spark-drv-local-conf-map
